//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Backend_Project
{
    using System;
    using System.Collections.Generic;
    
    public partial class AdminRights
    {
        public int idAdminRight { get; set; }
        public int idTypeRole { get; set; }
        public int idSystemLevel { get; set; }
        public bool BasicRights { get; set; }
        public bool ClassesRights { get; set; }
        public bool PlanningRights { get; set; }
        public bool MarksRights { get; set; }
        public bool InternshipOffersRights { get; set; }
        public bool InternshipConventionsRights { get; set; }
        public bool ImpersonationRights { get; set; }
        public bool LogsRights { get; set; }
        public bool ImportationRights { get; set; }
        public bool PreregistrationRights { get; set; }
        public bool AlterationDataRights { get; set; }
        public bool AcademicLifeRights { get; set; }
        public bool SecurityRights { get; set; }
        public bool MattersCoursesPlansRights { get; set; }
    
        public virtual SystemLevels SystemLevels { get; set; }
        public virtual TypesRoles TypesRoles { get; set; }
    }
}
