//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Backend_Project
{
    using System;
    using System.Collections.Generic;
    
    public partial class BusinessEntities
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public BusinessEntities()
        {
            this.ClientsDataModificationRequests = new HashSet<ClientsDataModificationRequests>();
            this.ContactDetails = new HashSet<ContactDetails>();
            this.Courses = new HashSet<Courses>();
            this.Events = new HashSet<Events>();
            this.Informations = new HashSet<Informations>();
            this.InternshipConventionRequests = new HashSet<InternshipConventionRequests>();
            this.JoinEntityClass = new HashSet<JoinEntityClass>();
            this.JoinEntityMessage = new HashSet<JoinEntityMessage>();
            this.LogsAlteration = new HashSet<LogsAlteration>();
            this.LogsCompetences = new HashSet<LogsCompetences>();
            this.LogsPreEnrolment = new HashSet<LogsPreEnrolment>();
            this.Marks = new HashSet<Marks>();
            this.Roles = new HashSet<Roles>();
        }
    
        public int idBusinessEntity { get; set; }
        public int idSalutation { get; set; }
        public int idTypeBusinessEntity { get; set; }
        public int idSystemLevel { get; set; }
        public string IDBoard { get; set; }
        public string Name { get; set; }
        public string FirstName { get; set; }
        public string SurName { get; set; }
        public string PhotoPath { get; set; }
        public Nullable<System.DateTime> DateOfBirth { get; set; }
        public string PlaceOfBirth { get; set; }
        public string Nationality { get; set; }
        public string CountryOfBirth { get; set; }
        public string Comments { get; set; }
        public string CardTokenID { get; set; }
    
        public virtual Salutations Salutations { get; set; }
        public virtual SystemLevels SystemLevels { get; set; }
        public virtual TypesBusinessEntities TypesBusinessEntities { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ClientsDataModificationRequests> ClientsDataModificationRequests { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ContactDetails> ContactDetails { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Courses> Courses { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Events> Events { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Informations> Informations { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<InternshipConventionRequests> InternshipConventionRequests { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<JoinEntityClass> JoinEntityClass { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<JoinEntityMessage> JoinEntityMessage { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<LogsAlteration> LogsAlteration { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<LogsCompetences> LogsCompetences { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<LogsPreEnrolment> LogsPreEnrolment { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Marks> Marks { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Roles> Roles { get; set; }
    }
}
