//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Backend_Project
{
    using System;
    using System.Collections.Generic;
    
    public partial class ClientsDataModificationRequests
    {
        public int idRequest { get; set; }
        public int idBusinessEntity { get; set; }
        public int idMessage { get; set; }
        public int idTargetedEntry { get; set; }
        public string TargetedTable { get; set; }
        public System.DateTime RequestDate { get; set; }
        public string MetaData { get; set; }
    
        public virtual BusinessEntities BusinessEntities { get; set; }
        public virtual Messages Messages { get; set; }
    }
}
