//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Backend_Project
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class IDBoardDb : DbContext
    {
        public IDBoardDb()
            : base("name=IDBoardDb")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<AdminRights> AdminRights { get; set; }
        public virtual DbSet<Aspects> Aspects { get; set; }
        public virtual DbSet<AspectsGlobalization> AspectsGlobalization { get; set; }
        public virtual DbSet<BusinessEntities> BusinessEntities { get; set; }
        public virtual DbSet<Chapters> Chapters { get; set; }
        public virtual DbSet<Classes> Classes { get; set; }
        public virtual DbSet<ClientsDataModificationRequests> ClientsDataModificationRequests { get; set; }
        public virtual DbSet<Competences> Competences { get; set; }
        public virtual DbSet<CompetencesStatus> CompetencesStatus { get; set; }
        public virtual DbSet<CompetencesStatusGlobalization> CompetencesStatusGlobalization { get; set; }
        public virtual DbSet<ContactDetails> ContactDetails { get; set; }
        public virtual DbSet<Courses> Courses { get; set; }
        public virtual DbSet<Domains> Domains { get; set; }
        public virtual DbSet<DomainsGlobalization> DomainsGlobalization { get; set; }
        public virtual DbSet<Events> Events { get; set; }
        public virtual DbSet<Informations> Informations { get; set; }
        public virtual DbSet<InternshipContacts> InternshipContacts { get; set; }
        public virtual DbSet<InternshipConventionRequests> InternshipConventionRequests { get; set; }
        public virtual DbSet<InternshipOffers> InternshipOffers { get; set; }
        public virtual DbSet<JoinAspectDomain> JoinAspectDomain { get; set; }
        public virtual DbSet<JoinEntityClass> JoinEntityClass { get; set; }
        public virtual DbSet<JoinEntityMessage> JoinEntityMessage { get; set; }
        public virtual DbSet<JoinMatterDomain> JoinMatterDomain { get; set; }
        public virtual DbSet<JoinOfferClass> JoinOfferClass { get; set; }
        public virtual DbSet<Languages> Languages { get; set; }
        public virtual DbSet<LockedAccounts> LockedAccounts { get; set; }
        public virtual DbSet<LogsAlteration> LogsAlteration { get; set; }
        public virtual DbSet<LogsCompetences> LogsCompetences { get; set; }
        public virtual DbSet<LogsConnection> LogsConnection { get; set; }
        public virtual DbSet<LogsPreEnrolment> LogsPreEnrolment { get; set; }
        public virtual DbSet<Marks> Marks { get; set; }
        public virtual DbSet<Matters> Matters { get; set; }
        public virtual DbSet<MattersGlobalization> MattersGlobalization { get; set; }
        public virtual DbSet<Messages> Messages { get; set; }
        public virtual DbSet<Roles> Roles { get; set; }
        public virtual DbSet<Salutations> Salutations { get; set; }
        public virtual DbSet<SalutationsGlobalization> SalutationsGlobalization { get; set; }
        public virtual DbSet<Sites> Sites { get; set; }
        public virtual DbSet<sysdiagrams> sysdiagrams { get; set; }
        public virtual DbSet<SystemLevels> SystemLevels { get; set; }
        public virtual DbSet<SystemLevelsGlobalization> SystemLevelsGlobalization { get; set; }
        public virtual DbSet<TypesBusinessEntities> TypesBusinessEntities { get; set; }
        public virtual DbSet<TypesBusinessEntitiesGlobalization> TypesBusinessEntitiesGlobalization { get; set; }
        public virtual DbSet<TypesCourses> TypesCourses { get; set; }
        public virtual DbSet<TypesCoursesGlobalization> TypesCoursesGlobalization { get; set; }
        public virtual DbSet<TypesEvaluations> TypesEvaluations { get; set; }
        public virtual DbSet<TypesEvaluationsGlobalization> TypesEvaluationsGlobalization { get; set; }
        public virtual DbSet<TypesEvents> TypesEvents { get; set; }
        public virtual DbSet<TypesEventsGlobalization> TypesEventsGlobalization { get; set; }
        public virtual DbSet<TypesInformations> TypesInformations { get; set; }
        public virtual DbSet<TypesInformationsGlobalization> TypesInformationsGlobalization { get; set; }
        public virtual DbSet<TypesInternships> TypesInternships { get; set; }
        public virtual DbSet<TypesInternshipsGlobalization> TypesInternshipsGlobalization { get; set; }
        public virtual DbSet<TypesRoles> TypesRoles { get; set; }
        public virtual DbSet<TypesRolesGlobalization> TypesRolesGlobalization { get; set; }
    }
}
