//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Backend_Project
{
    using System;
    using System.Collections.Generic;
    
    public partial class Informations
    {
        public int idInformation { get; set; }
        public int idBusinessEntity { get; set; }
        public int idTypeInformation { get; set; }
        public int idSystemLevel { get; set; }
        public string Value { get; set; }
        public System.DateTime DateStart { get; set; }
        public Nullable<System.DateTime> DateEnd { get; set; }
    
        public virtual BusinessEntities BusinessEntities { get; set; }
        public virtual SystemLevels SystemLevels { get; set; }
        public virtual TypesInformations TypesInformations { get; set; }
    }
}
