//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Backend_Project
{
    using System;
    using System.Collections.Generic;
    
    public partial class InternshipOffers
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public InternshipOffers()
        {
            this.JoinOfferClass = new HashSet<JoinOfferClass>();
        }
    
        public int idInternshipOffer { get; set; }
        public int idTypeInternship { get; set; }
        public string Reference { get; set; }
        public string Title { get; set; }
        public string MissionSummary { get; set; }
        public string CompanyName { get; set; }
        public string Duration { get; set; }
        public System.DateTime DateStart { get; set; }
        public Nullable<System.DateTime> DateEnd { get; set; }
        public string Contact { get; set; }
        public string ContactPhone { get; set; }
        public string ContactMail { get; set; }
        public string Address1 { get; set; }
        public string Address2 { get; set; }
        public string PostalCode { get; set; }
        public string City { get; set; }
        public string Country { get; set; }
    
        public virtual TypesInternships TypesInternships { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<JoinOfferClass> JoinOfferClass { get; set; }
    }
}
