//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Backend_Project
{
    using System;
    using System.Collections.Generic;
    
    public partial class InternshipConventionRequests
    {
        public int idRequest { get; set; }
        public int idRepresentative { get; set; }
        public int idTutor { get; set; }
        public int idStudent { get; set; }
        public int idTypeInternship { get; set; }
        public int idLanguage { get; set; }
        public int Status { get; set; }
        public System.DateTime DateCreation { get; set; }
        public Nullable<System.DateTime> DateEdition { get; set; }
        public Nullable<System.DateTime> DateReturn { get; set; }
        public System.DateTime DateStart { get; set; }
        public System.DateTime DateEnd { get; set; }
        public string FieldsToModify { get; set; }
        public string DailyTasks { get; set; }
        public string TechnologicalEnvironment { get; set; }
        public string TeachingGoals { get; set; }
        public string Company { get; set; }
        public string Phone { get; set; }
        public string Fax { get; set; }
        public string Mail { get; set; }
        public string WebSite { get; set; }
        public decimal Wage { get; set; }
        public bool TypeWage { get; set; }
        public string Currency { get; set; }
        public int WagePaymentPeriod { get; set; }
        public string Comments { get; set; }
        public string Address1 { get; set; }
        public string Address2 { get; set; }
        public string PostalCode { get; set; }
        public string City { get; set; }
        public string Country { get; set; }
    
        public virtual BusinessEntities BusinessEntities { get; set; }
        public virtual InternshipContacts InternshipContacts { get; set; }
        public virtual InternshipContacts InternshipContacts1 { get; set; }
        public virtual Languages Languages { get; set; }
        public virtual TypesInternships TypesInternships { get; set; }
    }
}
