//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Backend_Project
{
    using System;
    using System.Collections.Generic;
    
    public partial class JoinEntityClass
    {
        public int idJoin { get; set; }
        public int idBusinessEntity { get; set; }
        public int idClass { get; set; }
    
        public virtual BusinessEntities BusinessEntities { get; set; }
        public virtual Classes Classes { get; set; }
    }
}
