//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Backend_Project
{
    using System;
    using System.Collections.Generic;
    
    public partial class Languages
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Languages()
        {
            this.AspectsGlobalization = new HashSet<AspectsGlobalization>();
            this.CompetencesStatusGlobalization = new HashSet<CompetencesStatusGlobalization>();
            this.DomainsGlobalization = new HashSet<DomainsGlobalization>();
            this.InternshipConventionRequests = new HashSet<InternshipConventionRequests>();
            this.MattersGlobalization = new HashSet<MattersGlobalization>();
            this.SalutationsGlobalization = new HashSet<SalutationsGlobalization>();
            this.SystemLevelsGlobalization = new HashSet<SystemLevelsGlobalization>();
            this.TypesEvaluationsGlobalization = new HashSet<TypesEvaluationsGlobalization>();
            this.TypesCoursesGlobalization = new HashSet<TypesCoursesGlobalization>();
            this.TypesBusinessEntitiesGlobalization = new HashSet<TypesBusinessEntitiesGlobalization>();
            this.TypesEventsGlobalization = new HashSet<TypesEventsGlobalization>();
            this.TypesInformationsGlobalization = new HashSet<TypesInformationsGlobalization>();
            this.TypesInternshipsGlobalization = new HashSet<TypesInternshipsGlobalization>();
            this.TypesRolesGlobalization = new HashSet<TypesRolesGlobalization>();
        }
    
        public int idLanguage { get; set; }
        public string UICulture { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<AspectsGlobalization> AspectsGlobalization { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CompetencesStatusGlobalization> CompetencesStatusGlobalization { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DomainsGlobalization> DomainsGlobalization { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<InternshipConventionRequests> InternshipConventionRequests { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<MattersGlobalization> MattersGlobalization { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SalutationsGlobalization> SalutationsGlobalization { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SystemLevelsGlobalization> SystemLevelsGlobalization { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TypesEvaluationsGlobalization> TypesEvaluationsGlobalization { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TypesCoursesGlobalization> TypesCoursesGlobalization { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TypesBusinessEntitiesGlobalization> TypesBusinessEntitiesGlobalization { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TypesEventsGlobalization> TypesEventsGlobalization { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TypesInformationsGlobalization> TypesInformationsGlobalization { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TypesInternshipsGlobalization> TypesInternshipsGlobalization { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TypesRolesGlobalization> TypesRolesGlobalization { get; set; }
    }
}
