//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Backend_Project
{
    using System;
    using System.Collections.Generic;
    
    public partial class LockedAccounts
    {
        public int idLockedAccount { get; set; }
        public string Criteria { get; set; }
        public int CriteriaType { get; set; }
        public System.DateTime DateIssued { get; set; }
        public string IPAddress { get; set; }
    }
}
