//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Backend_Project
{
    using System;
    using System.Collections.Generic;
    
    public partial class LogsCompetences
    {
        public int idLogCompetence { get; set; }
        public int idBusinessEntity { get; set; }
        public int idCompetence { get; set; }
        public int idCompetenceStatus { get; set; }
        public System.DateTime Date { get; set; }
    
        public virtual BusinessEntities BusinessEntities { get; set; }
        public virtual Competences Competences { get; set; }
        public virtual CompetencesStatus CompetencesStatus { get; set; }
    }
}
