//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Backend_Project
{
    using System;
    using System.Collections.Generic;
    
    public partial class Marks
    {
        public int idMark { get; set; }
        public int idBusinessEntity { get; set; }
        public int idMatter { get; set; }
        public int idClass { get; set; }
        public int idTypeEvaluation { get; set; }
        public double Coefficient { get; set; }
        public double Value { get; set; }
        public string Comments { get; set; }
        public Nullable<System.DateTime> DateCreation { get; set; }
        public bool IsJustifiedAbsence { get; set; }
    
        public virtual BusinessEntities BusinessEntities { get; set; }
        public virtual Classes Classes { get; set; }
        public virtual Matters Matters { get; set; }
        public virtual TypesEvaluations TypesEvaluations { get; set; }
    }
}
