//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Backend_Project
{
    using System;
    using System.Collections.Generic;
    
    public partial class Roles
    {
        public int idRole { get; set; }
        public int idBusinessEntity { get; set; }
        public int idTypeRole { get; set; }
        public int idSite { get; set; }
        public Nullable<int> idLinkedEntity { get; set; }
        public System.DateTime DateStart { get; set; }
        public Nullable<System.DateTime> DateEnd { get; set; }
    
        public virtual BusinessEntities BusinessEntities { get; set; }
        public virtual Sites Sites { get; set; }
        public virtual TypesRoles TypesRoles { get; set; }
    }
}
