//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Backend_Project
{
    using System;
    using System.Collections.Generic;
    
    public partial class TypesRoles
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public TypesRoles()
        {
            this.AdminRights = new HashSet<AdminRights>();
            this.Roles = new HashSet<Roles>();
            this.TypesRolesGlobalization = new HashSet<TypesRolesGlobalization>();
        }
    
        public int idTypeRole { get; set; }
        public string TypeDefaultValue { get; set; }
        public bool IsStudent { get; set; }
        public bool IsAdvanceEnrolled { get; set; }
        public bool IsTeacher { get; set; }
        public bool IsCandidate { get; set; }
        public bool IsRepresentative { get; set; }
        public bool IsTutor { get; set; }
        public bool IsRelative { get; set; }
        public string ClassName { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<AdminRights> AdminRights { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Roles> Roles { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TypesRolesGlobalization> TypesRolesGlobalization { get; set; }
    }
}
